# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_version = "202112.19.0"
  #config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = "jenkinsV"
  #config.vm.network "public_network", ip: "192.168.1.100"
  config.vm.network "public_network"
  config.vm.define "jenkinsV"
  config.vm.network "forwarded_port", guest: 8080, host: 8090, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 22, host: 9922, protocol: "tcp"
  #config.vm.synced_folder "D:\share\", "/mnt/"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
  end


  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    echo "Install common tools"
    apt-get install -y nano git
    echo "Install Java and Maven"
    apt-get install -y openjdk-11-jdk openjdk-11-jdk-headless maven
    echo "Install Ruby"
    apt-get install -y ruby
    echo "Install Python 2"
    apt-get install -y python python-pip
    echo "Install Python 3"
    apt-get install -y python3 python3-pip
    #Docker instalation
    echo "install Docker"
    sudo apt-get install     ca-certificates     curl     gnupg     lsb-release
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o \
    /usr/share/keyrings/docker-archive-keyring.gpg
    echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io -y

    if [ ! -f /usr/bin/nodejs ]; then
        curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        apt-get install -y nodejs
        sudo apt-get install -y build-essential
        npm install -g grunt-cli gulp-cli bower
    fi
    if [ ! -d /var/lib/jenkins ]; then
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
        if [ ! -f /etc/apt/sources.list.d/jenkins.list ]; then
            echo "deb https://pkg.jenkins.io/debian-stable binary/" >> /etc/apt/sources.list.d/jenkins.list
        fi
        apt-get update
        apt-get install jenkins -y
        #add user Jenkins to Docker group and restart jenkins
        sudo adduser jenkins docker
        sudo systemctl restart jenkins
        if [ -f /var/lib/jenkins/secrets/initialAdminPassword ]; then
          echo "initialAdminPassword:"
          cat /var/lib/jenkins/secrets/initialAdminPassword
        fi
    fi
  SHELL
end
